name: CI Test & Security Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-and-scan:
    runs-on: ubuntu-latest
    env:
      API_URL: http://localhost:8080

    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.14'
    
      - name: Generate SECRET_KEY
        id: generate_secret
        run: |
            echo "SECRET_KEY=$(python -c 'import secrets; print(secrets.token_urlsafe(32))')" >> $GITHUB_OUTPUT

      - name: Build Docker image
        run: docker build -t dev-sec-ops/api-rest-crud .

      - name: Create Docker network
        run: docker network create zap-net || true

      - name: Run API container
        run: |
            docker run -d --name api --network zap-net -p 8080:80 \
                -e SQLALCHEMY_DATABASE_URL="sqlite:////usr/src/app/test.db" \
                -e SECRET_KEY="${{ steps.generate_secret.outputs.SECRET_KEY }}" \
                dev-sec-ops/api-rest-crud

      - name: Wait for API to be ready
        run: |
          echo "Waiting for API to be ready..."
          for i in {1..30}; do
            if curl -f $API_URL; then
              echo "API is up!"
              exit 0
            fi
            sleep 2
          done
          echo "API failed to start in time"
          docker logs api
          exit 1

      - name: Install test dependencies
        run: pip install pytest requests

      - name: Run pytest to create admin & get token
        id: auth
        run: |
          pytest tests/auth_flow.py -s
     
      - name: Display token
        run: echo "The admin token is ${{ steps.auth.outputs.token }}"
